### ISSUE TITLE
First layer is .20 for 0.5 mm profile and .15 mm for others ?

### ISSUE THREAD

**Issue by ChrisP-Git** [prusa3d/Slic3r-settings#1]
Hi,

just notice that the first layer remain .20 for the .5 mm profile (0.05mm DETAIL.ini) on the mk2:
first_layer_height = 0.2

Where everywhere else it's properly set to 0.15:
first_layer_height = 0.15

**Comment by jindrichbenes** [comment]
Thank you, I happened to notice it myself. It will be fixed in next release.
