### ISSUE TITLE
Errors in print settings?

### ISSUE THREAD

**Issue by Hugoz12** [prusa3d/Slic3r-settings#12]
In this setting file: 
https://github.com/prusa3d/Slic3r-settings/blob/master/Slic3r%20settings%20MK2/print/0.20mm%20NORMAL.ini

support_material_extrusion_width = 0.35

This is smaller than the 0.4 nozzle. Is this correct?

In this setting file: 
https://github.com/prusa3d/Slic3r-settings/blob/master/Slic3r%20settings%20MK2/print/0.15mm%20OPTIMAL.ini

top_infill_extrusion_width = 0.45

But in the update 1.36.1 you say it should be 1x nozzle dmr = 0.4mm

first_layer_extrusion_width = 0.42

And this 0.45mm.

**Comment by jindrichbenes** [comment]
support_material_extrusion_width is 0.35 for easier support removal. You may try to change it to 0.45 and do some comparison prints.
