### ISSUE TITLE
Extreme retraction after print

### ISSUE THREAD

**Issue by Thijxx** [prusa3d/Slic3r-settings#13]
With the default settings downloaded here for the MK2 on 1.75 PLA there is some kind of after-print issue with retraction. The wheel taking the filament eats into the filament after each print so I have to open the extruder to cut the filament and load it again. It does not seem to be influenced by more or less tension on the screws. So, printing goes well but after the printing the filament gets deformed..

**Comment by m-Th** [comment]
I experience this also; however I am not so sure about the cause....

**Comment by Thijxx** [comment]
For me it was solved by upgrading the firmware, resetting to factory defaults, double checking the right Slic3r settings ( I had the multi extruder by mistake on my single extruder printer) and I also reset the tension screws on the feeder, had them too tight.

**Comment by jindrichbenes** [comment]
MultiMaterial settings do have different retraction and end gcode, where filament retracts about 10 cm back into 4y splitter. This might have caused the issue.
