### ISSUE TITLE
printer .ini filename seems to be wrong

### ISSUE THREAD

**Issue by tuxmobil** [prusa3d/Slic3r-settings#16]
In Slic3r settings MK2/slic3r.ini the referenced printer filename seems to be wrong. 
"with Z hop" doesn't exist anymore.

**Comment by jindrichbenes** [comment]
The "with Z hop" description was removed, as Z-hop is on by default now. The "color print" settings, which had z-hop off since Colorprint post processor couldn't handle the z-hop value, was removed completely, since colorprint can handle z-hop now.
