### ISSUE TITLE
Start with heating bed instead of extruder

### ISSUE THREAD

**Issue by ManuGithubSteam** [prusa3d/Slic3r-settings#23]
Hi

I read a lot of discussions about oozing nozzles and als here in the prusa git. and AFIAK there is no real solution yet.

But the problem can be reduced:
- The heatbed takes way longer to heat up -> Heat it up first

Therefore just heat the bed beforehand and it reduced the idle time of the extruder a bit, because it has not to wait for the bed.

This helps in my setting with PETG a lot.

I just switched the two lines in the Gcode section.

This could be used as a workaround till there is a better solution

**Comment by jindrichbenes** [comment]
Wait for heatbed temperature, then start heating nozzle or heating both together are two options, both with their pros. For now, we will stay with both heatbed and nozzle warming up at the same time.
