### ISSUE TITLE
User modification/settings missing after upgrading Drivers

### ISSUE THREAD

**Issue by 3d-gussner** [prusa3d/Slic3r-settings#26]
I like the idea of having Slic3r settings versions, but after updating/upgrading the drivers modifications and new filament settings aren't available anymore due to the new settings folder being used.

It would be great
1. To **notify** the user that user modifications are gone with the installation and may need manual adjustment.
2. I know that this is ambitious but a merge wizard would be great.

My workaround is to use winmerge to see the differences and manually modifying settings to my needs.
Dialing in Filament temps and M900 K values, print and print settings takes a while so it is a pity that these are "gone" after the upgrade.

I know that most people will be fine with the default print settings.

**Comment by rtyr** [comment]
I believe this is outdated, custom settings are now preserved after update. Closing.
