### ISSUE TITLE
3 layer skirt is causing more issues than it solves

### ISSUE THREAD

**Issue by jasminl303** [prusa3d/Slic3r-settings#27]
Sometimes the priming strip is not enough to get the filament correctly set for the first layer.

In these cases the skirt acts as an extra priming strip. If something goes bad at this point you could remove the skirt while printing, the objects first layer could continue printing correctly and the print was saved.

With the 3 layer skirt, the print can fail at the second or third layer..  you cannot touch the first layer skirt at all. So the entire print depends on the skirt's first layer to be as good as the actual objects first layer.

Can we go back to skirt_height=1 ?

**Comment by jindrichbenes** [comment]
We will leave the skirt_height=3 for now, since 3 skirts make it way easier to remove both from classical PEI  and steel sheets . Please try to adjust your Z.
