### ISSUE TITLE
Please add settings with support material

### ISSUE THREAD

**Issue by SimplicityGuy** [prusa3d/Slic3r-settings#28]
On the SD card that ships with the MK2S, there is a model `PLA_Triceratops_Skull_150um_4H.gcode` that prints with support material. It would be nice to see these settings since sometimes prints require supports. So, can these be added into the Slic3r distribution please?

**Comment by jindrichbenes** [comment]
These settings are already there, you just need to go to print settings > support material and check Generate support material.
