### ISSUE TITLE
latest slic3r.init contains merge mistake

### ISSUE THREAD

**Issue by pieterbos** [prusa3d/Slic3r-settings#4]
It contains <<<<<<< , ======== and >>>>>> that indicates something went wrong merging :)

**Comment by bubnikv** [comment]
Thanks for heads up.

**Comment by jindrichbenes** [comment]
Is it better now?

**Comment by bubnikv** [comment]
It has been fixed by https://github.com/prusa3d/Slic3r-settings/commit/d1b295bf2f2d3e037528a53b71ae6eab913297e3
Thanks
