### ISSUE TITLE
Profiles for 0.6 mm nozzle

### ISSUE THREAD

**Issue by probonopd** [prusa3d/Slic3r-settings#41]
- Could we have a 100mms Linear Advance for 0.6mm nozzle?
- Could we have a 0.45 mm layer height with 100mms Linear Advance for 0.8mm nozzle?

**Comment by rtyr** [comment]
We don't plan such profiles for now. We have recently released new profiles for 0.6mm nozzle for MK3. Other thing is that we have to stay within volumetric speed limit of V6 hotend.
