### ISSUE TITLE
Printer Settings | Original Prusa i3 MK3 | Bed Size is Incorrect 

### ISSUE THREAD

**Issue by Deneteus** [prusa3d/Slic3r-settings#48]
The default bed size in Prusa Slic3r edition is showing me 250x210 instead of 250x250.

![image](https://user-images.githubusercontent.com/6380390/45585649-7402e580-b8ad-11e8-8905-d02023f33d40.png)

**Comment by Deneteus** [comment]
Apparently there are a few places that have posted the wrong bed size.

**Comment by haleypearse** [comment]
The prusa actually goes to 212 on the y axis, at which it seems to be firmware-limited. Perhaps this 2mm could be gained...
