### ISSUE TITLE
Printing problem with many times cover layer in Version 1.41.0

### ISSUE THREAD

**Issue by Devilscave** [prusa3d/Slic3r-settings#55]
I want to print four almost identical parts, all have a hole in the middle, but in one of them the cover layer is only indicated with one plane, all other three are calculated correctly. What can I do against it? See pictures.

[Level 40](https://scontent-frx5-1.xx.fbcdn.net/v/t1.0-9/44439565_1900526060033233_4270706112371621888_o.jpg?_nc_cat=108&_nc_ht=scontent-frx5-1.xx&oh=046b1803e7f49480c37d29e4481a0187&oe=5C53DF00)
[Level 41](https://scontent-frx5-1.xx.fbcdn.net/v/t1.0-9/44370435_1900526110033228_1432878390766993408_o.jpg?_nc_cat=101&_nc_ht=scontent-frx5-1.xx&oh=1d5755ef19c02ec13dda4bf001cf0d16&oe=5C505C71)
[Level 42](https://scontent-frx5-1.xx.fbcdn.net/v/t1.0-9/44489507_1900526146699891_9118154383303901184_o.jpg?_nc_cat=110&_nc_ht=scontent-frx5-1.xx&oh=ffebd5474ef3cb0edd0e6f0641b50610&oe=5C40D8F8)
[Level 44](https://scontent-frx5-1.xx.fbcdn.net/v/t1.0-9/44647818_1900526083366564_107844451254140928_o.jpg?_nc_cat=106&_nc_ht=scontent-frx5-1.xx&oh=cfcdff0f875f9e50e1f237063b3d62d5&oe=5C4F4E20)
[Level 45](https://scontent-frx5-1.xx.fbcdn.net/v/t1.0-9/44650382_1900526183366554_1004204263368294400_o.jpg?_nc_cat=101&_nc_ht=scontent-frx5-1.xx&oh=9e4eeb3c81887e3f637ba4d20ae64a43&oe=5C482E18)

**Comment by bubnikv** [comment]
Please post to https://github.com/prusa3d/slic3r/issues , closing here.
Please post the exact Slic3r version and other details asked by the Slic3r issue tracker.
Please test with the latest Slic3r (1.41.1-rc) whether the issue was not solved already.
