### ISSUE TITLE
Add configuration for Steelfill

### ISSUE THREAD

**Issue by gyscos** [prusa3d/Slic3r-settings#64]
The page for steelfill filament (https://shop.prusa3d.com/en/filament/150-steelfill-filament-750g.html) says:

> Please use corresponding print settings in Slic3r

However, there is no setting for Colorfabb steelfill (though there is "Brass Bronze", and "Woodfill").

Could we add an entry for this? Or add it to "Brass Bronze" if it's the same config? Thanks!

**Comment by rtyr** [comment]
I will look into it. Thank you.

**Comment by rtyr** [comment]
Added to "Brass Bronze" notes, along with copperFill (0.4.2). Closing.
