### ISSUE TITLE
Request: Random negative Y offset for purge line

### ISSUE THREAD

**Issue by xenoxaos** [prusa3d/Slic3r-settings#67]
I've noticed that I'm seeing degradation in my PEI sheet most at the initial purge line. This is by default in the start GCODE and set to print at Y=-3. Is there a way to randomize the offset between say -2mm and -4mm to reduce the wear on the PEI?

**Comment by rtyr** [comment]
Hi. No it is unfortunately not possible. I am not sure if random value from -2 to -4 would make a big difference.
