### ISSUE TITLE
Skirt height for easier removal

### ISSUE THREAD

**Issue by yschroeder** [prusa3d/Slic3r-settings#7]
This could save some PEI sheets from damage:

If you set the skirt height in the printing profile higher, for example three layers for `0.20mm NORMAL` it will results in 0.6mm high skirt which is much easier to remove and results in less residue material on the PEI sheet. You can just remove it with your fingernail then.

The amount of additional material needed for this comfort feature is minimal as well as impact on printing time.

You should consider this to make printing easier (as some materials stick really well to the PEI and single layers are hard to remove).

**Comment by jindrichbenes** [comment]
Skirt height 3 has been implemented in latest settings
